In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import ipywidgets as widgets
import csv

In [3]:
df_terres = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2018/FAOSTAT Type de terres.csv")

# Supprimer les colonnes inutiles
df_terres = df_terres[['Area', 'Year', 'Item', 'Value']]
df_terres[['Value']] = df_terres[['Value']].astype(np.int64)
df_terres['Value'] = df_terres['Value'].apply(lambda x: str(x) + " " + "%")

df_terres.insert(loc=0, column='Area_1', value=df_terres['Area'])
df_terres = df_terres.set_index('Area_1')

df_pays = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Version 2/CSV/Pays.csv")
df_pays.insert(loc=0, column='Area_1', value=df_pays['Area'])
df_pays = df_pays.set_index('Area_1')

df_terres_7 = df_terres[df_terres['Item'].str.contains('Arable land')]
df_terres_7 = df_terres_7.rename(columns={"Value":'Arable land'})

df_terres_1 = df_terres[df_terres['Item'].str.contains('Land under permanent crops')]
df_terres_1 = df_terres_1.rename(columns={"Value":'Land under permanent crops'})

df_terres_2 = df_terres[df_terres['Item'].str.contains('Cropland')]
df_terres_2 = df_terres_2.rename(columns={"Value":'Cropland'})

df_terres_3 = df_terres[df_terres['Item'].str.contains('Land under perm. meadows and pastures')]
df_terres_3 = df_terres_3.rename(columns={"Value":'Land under perm. meadows and pastures'})

df_terres_4 = df_terres[df_terres['Item'].str.contains('Agriculture area actually irrigated')]
df_terres_4 = df_terres_4.rename(columns={"Value":'Agriculture area actually irrigated'})

df_terres_5 = df_terres[df_terres['Item'].str.contains('Land area equipped for irrigation')]
df_terres_5 = df_terres_5.rename(columns={"Value":'Land area equipped for irrigation'})

df_terres_6 = df_terres[df_terres['Item'].str.contains('Agriculture area under organic agric.')]
df_terres_6 = df_terres_6.rename(columns={"Value":'Agriculture area under organic agric.'})


df_entite_terres = pd.merge(df_pays, df_terres_7["Arable land"], how='left', left_index=True, right_index=True)
df_entite_terres = pd.merge(df_entite_terres, df_terres_1["Land under permanent crops"], how='left', left_index=True, right_index=True)
df_entite_terres = pd.merge(df_entite_terres, df_terres_2["Cropland"], how='left', left_index=True, right_index=True)
df_entite_terres = pd.merge(df_entite_terres, df_terres_3["Land under perm. meadows and pastures"], how='left', left_index=True, right_index=True)
df_entite_terres = pd.merge(df_entite_terres, df_terres_4["Agriculture area actually irrigated"], how='left', left_index=True, right_index=True)
df_entite_terres = pd.merge(df_entite_terres, df_terres_5["Land area equipped for irrigation"], how='left', left_index=True, right_index=True)
df_entite_terres = pd.merge(df_entite_terres, df_terres_6["Agriculture area under organic agric."], how='left', left_index=True, right_index=True)

liste = []

for i in range(255):
    liste.append(2018)
    
df_entite_terres = pd.merge(df_entite_terres, df_pays)
del df_entite_terres['Area']
df_entite_terres.insert(1, column= "Year", value=liste)
# df_entite_terres = df_entite_terres[['Area Code', 'Year', 'Arable land', "Land under permanent crops", "Cropland", "Land under perm. meadows and pastures", "Agriculture area actually irrigated", "Land area equipped for irrigation", "Agriculture area under organic agric."]]
df_entite_terres.insert(loc=0, column='Area_Code', value=df_entite_terres['Area Code'])
df_entite_terres = df_entite_terres.set_index('Area_Code')

df_meteo = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Version 2/CSV/MÃ©tÃ©o.csv")
df_meteo = df_meteo[df_meteo['Year'] == 2016]
df_meteo.insert(loc=0, column='Area_Code', value=df_meteo['Area Code'])
df_meteo = df_meteo.set_index('Area_Code')

# df_entite_terres = pd.merge(df_entite_terres, df_meteo[["Temperature (Â°C)", "Rainfall - (MM)"]], how='left', left_index=True, right_index=True)
df_entite_terres = df_entite_terres.reset_index(drop=True)

# Enregistrer le DataFrame dans un fichier csv
df_entite_terres.drop_duplicates(subset = "Area Code", keep = 'first', inplace=True)
# df_entite_terres.to_csv('CSV/Terres.csv', index=False, encoding="utf-8-sig", quoting=csv.QUOTE_NONNUMERIC)
df_entite_terres.to_csv('CSV/Terres.csv', index=False, sep=',', encoding="utf-8-sig")
df_entite_terres

,Area Code,Year,Arable land,Land under permanent crops,Cropland,Land under perm. meadows and pastures,Agriculture area actually irrigated,Land area equipped for irrigation,Agriculture area under organic agric.
0,2,2018,20 %,0 %,20 %,79 %,5 %,8 %,0 %
1,3,2018,52 %,7 %,59 %,40 %,14 %,30 %,0 %
2,4,2018,18 %,2 %,20 %,79 %,NaN,3 %,0 %
3,7,2018,8 %,0 %,9 %,90 %,NaN,0 %,NaN
4,8,2018,44 %,11 %,55 %,44 %,NaN,4 %,NaN
...,...,...,...,...,...,...,...,...,...
250,417,2018,0 %,NaN,0 %,99 %,NaN,NaN,NaN
251,440,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,469,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,480,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,484,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_terres= pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2018/FAOSTAT Type de terres.csv")
df_terres[df_terres["Item Code"] == 6621]

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,EL,Land use indicators,2,Afghanistan,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,20.31,Fc,Calculated data
7,EL,Land use indicators,3,Albania,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,52.07,Fc,Calculated data
14,EL,Land use indicators,4,Algeria,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,18.15,Fc,Calculated data
20,EL,Land use indicators,5,American Samoa,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,61.22,Fc,Calculated data
23,EL,Land use indicators,6,Andorra,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,4.41,Fc,Calculated data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,EL,Land use indicators,243,Wallis and Futuna Islands,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,16.67,Fc,Calculated data
1239,EL,Land use indicators,205,Western Sahara,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,0.08,Fc,Calculated data
1242,EL,Land use indicators,249,Yemen,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,4.69,Fc,Calculated data
1247,EL,Land use indicators,251,Zambia,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,15.94,Fc,Calculated data
1253,EL,Land use indicators,181,Zimbabwe,7208,Share in Agricultural land,6621,Arable land,2018,2018,%,24.69,Fc,Calculated data