In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import ipywidgets as widgets
import csv

In [3]:
df_sante = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2016/EspÃ©rance de vie.csv")
df_sante['Unnamed: 1'] = df_sante[1:]['Unnamed: 1'].apply(lambda x: int(x))
df_sante = df_sante.rename(columns = {'Unnamed: 0': 'Area', 'Unnamed: 1': 'Year','Life expectancy at birth (years)': 'Life expectancy at birth (Both)', 'Life expectancy at birth (years).1': 'Life expectancy at birth (Male)', 'Life expectancy at birth (years).2': 'Life expectancy at birth (Female)', 'Life expectancy at age 60 (years)': 'Life expectancy at age 60 (Both)', 'Life expectancy at age 60 (years).1': 'Life expectancy at age 60 (Male)', 'Life expectancy at age 60 (years).2': 'Life expectancy at age 60 (Female)', 'Healthy life expectancy (HALE) at birth (years)': 'Healthy life expectancy at birth (Both)', 'Healthy life expectancy (HALE) at birth (years).1': 'Healthy life expectancy at birth (Male)', 'Healthy life expectancy (HALE) at birth (years).2': 'Healthy life expectancy at birth (Female)', 'Healthy life expectancy (HALE) at age 60 (years)': 'Healthy life expectancy at age 60 (Both)', 'Healthy life expectancy (HALE) at age 60 (years).1': 'Healthy life expectancy at age 60 (Male)', 'Healthy life expectancy (HALE) at age 60 (years).2': 'Healthy life expectancy at age 60 (Female)'})
df_sante = df_sante[1:]
df_sante[['Year']] = df_sante[['Year']].astype(np.int64)
df_sante.insert(loc=0, column='Area_1', value=df_sante['Area'])
df_sante = df_sante.set_index('Area_1')

df_pays = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Version 2/CSV/Pays.csv")
df_pays.insert(loc=0, column='Area_1', value=df_pays['Area'])
df_pays = df_pays.set_index('Area_1')

df_sante = pd.merge(df_sante, df_pays)
df_sante = df_sante[['Area Code', 'Year', 'Life expectancy at birth (Both)', "Life expectancy at birth (Male)", "Life expectancy at birth (Female)", "Life expectancy at age 60 (Both)", "Life expectancy at age 60 (Male)", "Life expectancy at age 60 (Female)", "Healthy life expectancy at birth (Both)", "Healthy life expectancy at birth (Male)", "Healthy life expectancy at birth (Female)", "Healthy life expectancy at age 60 (Both)", "Healthy life expectancy at age 60 (Male)", "Healthy life expectancy at age 60 (Female)"]]

# Enregistrer le DataFrame dans un fichier csv
# df_sante.to_csv('CSV/SantÃ©.csv', index=False, encoding="utf-8-sig", quoting=csv.QUOTE_NONNUMERIC)
df_sante.to_csv('CSV/SantÃ©.csv', sep=',', encoding='utf-8-sig')
df_sante

,Area Code,Year,Life expectancy at birth (Both),Life expectancy at birth (Male),Life expectancy at birth (Female),Life expectancy at age 60 (Both),Life expectancy at age 60 (Male),Life expectancy at age 60 (Female),Healthy life expectancy at birth (Both),Healthy life expectancy at birth (Male),Healthy life expectancy at birth (Female),Healthy life expectancy at age 60 (Both),Healthy life expectancy at age 60 (Male),Healthy life expectancy at age 60 (Female)
0,2,2019,63.2,63.3,63.2,15.2,15.4,15.1,53.9,54.7,53.2,10.8,11.2,10.6
1,2,2015,61.7,61.0,62.3,15.6,15.7,15.5,52.6,52.8,52.4,11.2,11.5,10.9
2,2,2010,59.9,59.6,60.3,15.1,15.1,15.2,51.1,51.5,50.7,10.9,11.1,10.7
3,2,2000,55.0,54.6,55.4,13.9,13.6,14.2,46.8,46.9,46.6,10.2,10.2,10.1
4,3,2019,78.0,76.3,79.9,21.0,20.2,21.9,69.1,68.0,70.3,16.6,15.9,17.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,251,2000,44.5,43.7,45.2,13.2,11.6,14.7,39.0,38.6,39.3,10.0,8.9,11.1
729,181,2019,60.7,57.5,63.6,15.6,13.6,17.0,53.1,51.2,54.8,11.5,10.2,12.4
730,181,2015,58.5,55.7,61.0,15.1,13.2,16.5,51.2,49.6,52.6,11.2,9.9,12.0
731,181,2010,51.5,49.6,53.2,14.1,12.4,15.4,45.2,44.2,46.1,10.5,9.3,11.3
732,181,2000,46.6,45.1,48.1,14.4,11.7,17.1,41.0,40.4,41.8,10.6,8.7,12.4

,Area Code,Year,Life expectancy at birth (Both),Life expectancy at birth (Male),Life expectancy at birth (Female),Life expectancy at age 60 (Both),Life expectancy at age 60 (Male),Life expectancy at age 60 (Female),Healthy life expectancy at birth (Both),Healthy life expectancy at birth (Male),Healthy life expectancy at birth (Female),Healthy life expectancy at age 60 (Both),Healthy life expectancy at age 60 (Male),Healthy life expectancy at age 60 (Female)
0,2,2019,63.2,63.3,63.2,15.2,15.4,15.1,53.9,54.7,53.2,10.8,11.2,10.6
1,2,2015,61.7,61.0,62.3,15.6,15.7,15.5,52.6,52.8,52.4,11.2,11.5,10.9
2,2,2010,59.9,59.6,60.3,15.1,15.1,15.2,51.1,51.5,50.7,10.9,11.1,10.7
3,2,2000,55.0,54.6,55.4,13.9,13.6,14.2,46.8,46.9,46.6,10.2,10.2,10.1
4,3,2019,78.0,76.3,79.9,21.0,20.2,21.9,69.1,68.0,70.3,16.6,15.9,17.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,251,2000,44.5,43.7,45.2,13.2,11.6,14.7,39.0,38.6,39.3,10.0,8.9,11.1
729,181,2019,60.7,57.5,63.6,15.6,13.6,17.0,53.1,51.2,54.8,11.5,10.2,12.4
730,181,2015,58.5,55.7,61.0,15.1,13.2,16.5,51.2,49.6,52.6,11.2,9.9,12.0
731,181,2010,51.5,49.6,53.2,14.1,12.4,15.4,45.2,44.2,46.1,10.5,9.3,11.3
732,181,2000,46.6,45.1,48.1,14.4,11.7,17.1,41.0,40.4,41.8,10.6,8.7,12.4