In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import ipywidgets as widgets
import csv

In [5]:
df_pays = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2018/FAOSTAT NB Populations.csv")
df_pays = df_pays.drop(columns=["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Item", "Year Code", "Year", "Unit", "Value", "Flag", "Flag Description"])

df_sante = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2016/Espérance de vie.csv")
df_sante = df_sante[["Unnamed: 0"]]
df_sante.drop_duplicates(subset = "Unnamed: 0", keep = 'first', inplace=True)
df_sante = df_sante.reset_index(drop=True)

df_capital = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2018/FAOSTAT Investissement, Dépréciation, Stock Financier.csv")
df_capital = df_capital.drop(columns=["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Item", "Year Code", "Year", "Unit", "Value", "Flag", "Flag Description", "Note"])
df_capital.drop_duplicates(subset = "Area", keep = 'first', inplace=True)

df_nutrition = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2018/FAOSTAT NB Populations en sous-nutrition.csv")
df_nutrition = df_nutrition.drop(columns=["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Item", "Year Code", "Year", "Unit", "Value", "Flag", "Flag Description", "Note"])

df_pays = pd.concat([df_pays,df_capital, df_nutrition]).drop_duplicates().reset_index(drop=True)
df_pays['Area'] = df_pays['Area'].replace({"Democratic People's Republic of Korea": "North Korea", "Republic of Korea": "South Korea", " \(Plurinational State of\)":'',' Darussalam':'', 'Cabo Verde':'Cape Verde', 'Micronesia (Federated States of)': 'Federated States of Micronesia', 'Iran \(Islamic Republic of\)': 'Iran', 'République démocratique du Congo':'Democratic Republic of the Congo', 'Russian Federation':'Russia', 'Somalie':'Somalia', 'Libye':'Libya','Saint Kitts and Nevis':'St. Kitts and Nevis', 'Saint Lucia':'St. Lucia', 'Saint Vincent and the Grenadines':'St. Vincent and the Grenadines', 'Eswatini':'Swaziland', 'United Republic of Tanzania':'Tanzania', 'United Kingdom of Great Britain and Northern Ireland':'United Kingdom', 'Venezuela \(Bolivarian Republic of\)':'Venezuela', 'Timor-Leste':'Timor Leste', "Lao People's Democratic Republic":'Laos', 'Micronésie \(États fédérés de\)':'Federated States of Micronesia', 'Érythrée':'Eritrea', 'Guinée équatoriale':'Equatorial Guinea', 'Comores':'Comoros', 'Brunéi':'Brunei', 'Bhoutan':'Bhutan', 'Bahreïn':'Bahrain', 'Andorre': 'Andorra','Îles Marshall':'Marshall Islands', 'République arabe syrienne':'Syria', 'American Samoa':'Samoa'}, regex=True)
df_pays.drop_duplicates(subset = "Area Code", keep = 'first', inplace=True)

df_pluie = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2016/Pluie.csv", sep='\s*,\s*')
df_pluie = df_pluie.rename(columns = {'Country': 'Area'})

df_meteo = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2016/Météo.csv", sep='\s*,\s*')
df_meteo = df_meteo.rename(columns = {'Country': 'Area'})

df_terres = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2018/FAOSTAT Type de terres.csv")
df_terres = df_terres.rename(columns = {'Zone': 'Area'})

df_details_produit = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Version 2/CSV/Bilan Alimentaire.csv")

area = []
area_code = []
area_code_value = 351

for i in df_pluie['Area'].unique():
    if i not in df_pays['Area'].unique():
        area_code_value += 1
        area.append(i)
        area_code.append(area_code_value)

# for j in df_pays['Area'].unique():
#     if j not in df_pluie['Area'].unique():
#         area_code_value += 1
#         area.append(j)
#         area_code.append(area_code_value)

for k in df_terres['Area'].unique():
    if k not in df_pays['Area'].unique():
        area_code_value += 1
        area.append(k)
        area_code.append(area_code_value)
    
# for l in df_pays['Area'].unique():
#     if l not in df_terres['Area'].unique():
#         area_code_value += 1
#         area.append(l)
#         area_code.append(area_code_value)
        
for m in df_meteo['Area'].unique():
    if m not in df_pays['Area'].unique():
        area_code_value += 1
        area.append(m)
        area_code.append(area_code_value)
    
# for n in df_pays['Area'].unique():
#     if n not in df_meteo['Area'].unique():
#         area_code_value += 1
#         area.append(n)
#         area_code.append(area_code_value)

for o in df_details_produit['Area'].unique():
    if o not in df_pays['Area'].unique():
        area_code_value += 1
        area.append(o)
        area_code.append(area_code_value)

df_supp = pd.DataFrame({'Area Code':area_code, 'Area':area})
# df_pays = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Version 2/Pays.csv")
# df_pays = df_pays.append(df_supp)

df_pays = pd.concat([df_pays, df_supp])
df_pays = df_pays.reset_index(drop=True)
df_pays.drop_duplicates(subset = "Area", keep = 'first', inplace=True)
df_pays.drop_duplicates(subset = "Area Code", keep = 'first', inplace=True)


# Enregistrer le DataFrame dans un fichier csv
df_pays.to_csv('CSV/Pays.csv', index=False, sep=',', encoding="utf-8-sig")
df_pays

<ipython-input-5-c9efff20159a>:20: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_pluie = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2016/Pluie.csv", sep='\s*,\s*')
<ipython-input-5-c9efff20159a>:23: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_meteo = pd.read_csv("C:/Users/namor/Dropbox/Simplon/Programmation/Projet Fil rouge/Data/2016/Météo.csv", sep='\s*,\s*')

     Area Code                   Area
0            2            Afghanistan
1            3                Albania
2            4                Algeria
3            7                 Angola
4            8    Antigua and Barbuda
..         ...                    ...
254        397         Western Sahara
258        401  North North Macedonia
266        409         Czechoslovakia
277        420                   USSR
281        424           Yugoslav SFR

[255 rows x 2 columns]